Add priority attribute to processor tags
symfony/monolog-bundle pull request #353
Opened 2020-06-04 10:15 UTC by Erikvv

Currently you cannot determine the order in which processors are added, and thus called.

In other parts of symfony this is done through a "priority" attribute.

I have added this and I'm using this in a proprietary project.

2020-06-04 10:19 UTC, Erikvv commented on DependencyInjection/Compiler/AddProcessorsPass.php
> +
Below this line the code is identical to what it was, except 1 level less indented

2020-07-06 08:24 UTC, natepage commented
Any news on this PR, we have a project that requires this feature. Anything we can do to help make it move forward?

2021-03-21 17:07 UTC, jderusse requested changes
Symfony exposes a `PriorityTaggedServiceTrait` trait that provides all the logic you need in this PR.

This would also deserve an entry in the CHANGELOG

2021-03-21 21:04 UTC, Erikvv commented
I am no longer in the ecosystem. Someone else can make a new PR.

2021-03-21 21:04 UTC, closed without merging